// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package sqlc

import (
	"context"
	"time"
)

const createVoiceChannel = `-- name: CreateVoiceChannel :one
INSERT INTO channels (id, name, type, user_limit, bitrate, created_at)
VALUES (?, ?, 'voice', ?, ?, ?)
RETURNING id, name, type, user_limit, bitrate, created_at
`

type CreateVoiceChannelParams struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	UserLimit int64     `json:"user_limit"`
	Bitrate   int64     `json:"bitrate"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateVoiceChannel(ctx context.Context, arg CreateVoiceChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createVoiceChannel,
		arg.ID,
		arg.Name,
		arg.UserLimit,
		arg.Bitrate,
		arg.CreatedAt,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.UserLimit,
		&i.Bitrate,
		&i.CreatedAt,
	)
	return i, err
}

const listVoiceChannels = `-- name: ListVoiceChannels :many
SELECT id, name, type, user_limit, bitrate, created_at
FROM channels
WHERE type = 'voice'
ORDER BY created_at ASC
`

func (q *Queries) ListVoiceChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listVoiceChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.UserLimit,
			&i.Bitrate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
