// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package sqlc

import (
	"context"
	"time"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, channel_id, sender_id, content, created_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID        string    `json:"id"`
	ChannelID string    `json:"channel_id"`
	SenderID  string    `json:"sender_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ChannelID,
		arg.SenderID,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const getMessagesByChannelID = `-- name: GetMessagesByChannelID :many
SELECT id, channel_id, sender_id, content, created_at
FROM messages
WHERE channel_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetMessagesByChannelIDParams struct {
	ChannelID string `json:"channel_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

func (q *Queries) GetMessagesByChannelID(ctx context.Context, arg GetMessagesByChannelIDParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChannelID, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesByChannelIDWithSender = `-- name: GetMessagesByChannelIDWithSender :many
SELECT m.id, m.channel_id, m.sender_id, a.name as sender_name, m.content, m.created_at
FROM messages m
JOIN accounts a ON m.sender_id = a.id
WHERE m.channel_id = ?
ORDER BY m.created_at DESC
LIMIT ? OFFSET ?
`

type GetMessagesByChannelIDWithSenderParams struct {
	ChannelID string `json:"channel_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

type GetMessagesByChannelIDWithSenderRow struct {
	ID         string    `json:"id"`
	ChannelID  string    `json:"channel_id"`
	SenderID   string    `json:"sender_id"`
	SenderName string    `json:"sender_name"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) GetMessagesByChannelIDWithSender(ctx context.Context, arg GetMessagesByChannelIDWithSenderParams) ([]GetMessagesByChannelIDWithSenderRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChannelIDWithSender, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByChannelIDWithSenderRow
	for rows.Next() {
		var i GetMessagesByChannelIDWithSenderRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderID,
			&i.SenderName,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
